//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attendence3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Branch { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> RollNo { get; set; }
        public string PhoneNo { get; set; }
        public Nullable<int> Attendence { get; set; }
        public string Division { get; set; }
        public string Password { get; set; }
        public Nullable<int> WDDN { get; set; }
        public Nullable<int> AT { get; set; }
        public Nullable<int> AA { get; set; }
        public Nullable<int> MFP { get; set; }
        public Nullable<int> OS { get; set; }
        public Nullable<int> IsStudent { get; set; }
    }
}
